### ISSUE TITLE
Can't Use sv_cheats binds

### ISSUE THREAD

**Issue by ep4151** [Jbleezy/BO1-Reimagined#5]
ive done all the steps to enable sv cheats binds and it still wont work

**Comment by Jbleezy** [comment]
That is intended. Don't cheat on Reimagined.

**Comment by davtur19** [comment]
why force a person not to use cheats?
I wanted to use them to try the mod faster before playing with a friend
you can remove this line? https://github.com/Jbleezy/BO1-Reimagined/blob/3fd730fadac0a7437a02425f311adb4b225d00df/maps/_zombiemode.gsc#L1733
otherwise I do it myself but it is a useless hassle
